name: auto-zip
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  auto-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         chmod +x ./.github/workflows/createzips.sh
         ./.github/workflows/createzips.sh
        shell: bash
      - uses: EndBug/add-and-commit@v9
        with:
          message: ${{ github.event.head_commit.message }} (automated add zips action)
          default_author: github_actions
