name: auto-zip
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  auto-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         chmod +x ./.github/workflows/createzips.sh
         ./.github/workflows/createzips.sh
        shell: bash
